### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by kichuman28** [Joeljaison391/Blogz#7]
![Screenshot 2024-06-22 115803](https://github.com/Joeljaison391/Blogz/assets/97717315/6fb1e03b-b298-40e3-a99e-c6738c2fdf17)

**Comment by Joeljaison391** [comment]
This issue has  been resolved in commit [34a9b1eddb30f754025a14db6a1995823b2a5c27](https://github.com/Joeljaison391/Blogz/commit/34a9b1eddb30f754025a14db6a1995823b2a5c27).
